FROM php:7.2-fpm

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils \
        libbz2-dev \
        libjpeg-dev \
		libjpeg62-turbo-dev \
        libmcrypt-dev \
        libxml++2.6-dev \
        libcurl3-dev \
        libpq-dev \
        libfreetype6-dev \
        libwebp-dev \
        libpng-dev \
        libxpm-dev \
		libmcrypt-dev \
		libpng-dev \
		libmagickwand-dev \
        libmagickcore-dev \
        zlib1g-dev \
        libzip-dev \
        zip unzip python git \
	&& docker-php-ext-install curl mbstring xml zip gd \
    && docker-php-ext-configure zip --with-libzip \
    && docker-php-ext-install intl pdo mysqli pdo_mysql bcmath zip \
    && docker-php-ext-install pcntl \
    && pecl install imagick \
    && docker-php-ext-enable imagick \
    && pecl install xdebug && docker-php-ext-enable xdebug \
    && rm -rf /tmp/* /var/cache/apk/* \
    && rm -r /var/lib/apt/lists/* \

    && echo "error_reporting = E_ALL" >> /usr/local/etc/php/conf.d/xdebug_config.ini \
    && echo "display_startup_errors = On" >> /usr/local/etc/php/conf.d/xdebug_config.ini \
    && echo "display_errors = On" >> /usr/local/etc/php/conf.d/xdebug_config.ini \
    && echo "" >> /usr/local/etc/php/conf.d/xdebug_config.ini \
    && echo "[xdebug]" >> /usr/local/etc/php/conf.d/xdebug_config.ini \
    && echo "xdebug.idekey=\"PHPSTORM\"" >> /usr/local/etc/php/conf.d/xdebug_config.ini \
    && echo "xdebug.remote_port=9000" >> /usr/local/etc/php/conf.d/xdebug_config.ini \
    && echo "xdebug.remote_enable=1" >> /usr/local/etc/php/conf.d/xdebug_config.ini \
    && echo "xdebug.remote_autostart=1" >> /usr/local/etc/php/conf.d/xdebug_config.ini \

    &&  userdel -f www-data &&\
        if getent group www-data ; then groupdel www-data; fi &&\
        groupadd -g 1000 www-data &&\
        useradd -l -u 1000 -g www-data www-data &&\
        install -d -m 0755 -o www-data -g www-data /home/www-data &&\
        chown --changes --silent --no-dereference --recursive \
              --from=33:33 ${USER_ID}:${GROUP_ID} \
            /home/www-data \
     && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

USER www-data

RUN composer global require hirak/prestissimo

ENV PATH=${PATH}:/home/www-data/.composer/vendor/bin

WORKDIR /var/www